---
- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
  tags: [ system ]

- name: Installing Apache
  apt:
    update_cache: yes
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-bcmath      
      - php-curl
      - php-intl
      - php-bcmath
      - php-xml
      - php-zip 
  tags: [system]


#Apache Configuration 

- name: Create document root
  file:
    path: "/var/www/wordpress"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
  tags: [ apache ]

- name: Set up Apache VirtualHost
  template:
    src: "templates/apache.conf.j2"
    dest: "/etc/apache2/sites-available/wordpress"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Reload Apache
  tags: [ apache ]

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache
  tags: [ apache ]

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache
  tags: [ apache ]

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: Restart Apache
  tags: [ apache ]

  # UFW Configuration
- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp
  tags: [ system ]

 # WordPress Configuration
- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/"
    remote_src: yes
    creates: "/var/www/wordpress"
  tags: [ wordpress ]

- name: Set ownership
  file:
    path: "/var/www/wordpress"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ wordpress ]

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/wordpress/ -type d -exec chmod 750 {} \\;"
  tags: [ wordpress ]

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/wordpress/ -type f -exec chmod 640 {} \\;"
  tags: [ wordpress ]

- name: Set up wp-config
  template:
    src: "templates/wp-config2.php.j2"
    dest: "/var/www/wordpress/wp-config.php"
  tags: [ wordpress ]